name: Generate Snake Animation

on:
  schedule:
    # Run every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: assets/github-contribution-grid-snake.gif
          svg_out_path: assets/github-contribution-grid-snake.svg

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com.com
          git add assets/github-contribution-grid-snake.gif assets/github-contribution-grid-snake.svg
          git diff --staged --quiet || git commit -m "chore: update contribution snake animation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
